#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Hello World!
# The redirection must be a “301 Moved Permanently”

if ! nginx -v; then
        sudo apt -y update
        sudo apt install -y nginx
fi

new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "5i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
