#!/usr/bin/env bash
#	Write a Bash script that displays To infinity and beyond indefinitely.
#
#	Requirements:
#
#		In between each iteration of the loop, add a sleep 2

infinity=1

while  (( infinity )) 
do
	echo "To infinity and beyond"

	sleep 2
done
