#!/usr/bin/env bash
#   Write a Bash script that displays the content of the file /etc/passwd.

#   Your script should only display:

#       username
#       user id
#       Home directory path for the user
#   Requirements:

#       You must use the while loop (for and until are forbidden)


while IFS= read -r line; do
    # Check if the line contains a colon (:)
    if [[ "$line" == *":"* ]]; then
   
        echo "$line" | cut -d ':' -f 1,3,6
    elif [[ "$line" == *","* ]]; then
  
        echo "$line" | cut -d ',' -f 1,3,6
    elif [[ "$line" == *"_"* ]]; then
        echo  "$line" | cut -d ':' -f 1,3,6
    else
 
        echo "$line" | cut -d ';' -f 1,3,6

    fi
done </etc/passwd

