#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and:

#   displays 4 and then bad luck from China for the 4th loop iteration
#   displays 9 and then bad luck from Japan for the 9th loop iteration
#   displays 17 and then bad luck from Italy for the 17th loop iteration
#Requirements:
#   You must use the while loop (for and until are forbidden)
#   You must use the case statement


hour=0;

while [[ "$hour" -le 12 ]]; do
    echo "Hour: $hour"
    min=1
    while [[ "$min" -le 59 ]]; do
        echo "$min"
        ((min++))
    done
    (( hour++ ))
done
